site_name: Wet-Lab Protocol
repo_url: https://github.com/SitaoZ/wet-lab
site_author: "Sitao ZHU"
copyright: Copyright &copy; 2024-2025, Song Lab, WHU

nav:
- 写在前面: index.md
- 分子生物学技术:
    - 1-1. PCR: Introduction/1-1.md
    - 1-2. 分子克隆: Introduction/1-2.md
    - 1-3. 核酸电泳: error.md
    - 1-4. DNA/RNA提取: Introduction/1-4.ipynb
    - 1-5. 载体构建: error.md
- 免疫学技术:
    - 2-1. Western Blot: preprocess/2-1.ipynb
    - 2-2. 免疫组化: preprocess/2-2.ipynb
    - 2-3. ELISA: preprocess/2-3.ipynb
    - 2-4. 流式细胞术: preprocess/2-4.ipynb
    - 2-5. BIFC: preprocess/2-5.ipynb
- 生物化学技术:
    - 3-1. 酶学实验: Identifying cellular structure/3-1.ipynb
    - 3-2. 蛋白质分离与纯化: Identifying cellular structure/3-2.ipynb
    - 3-3. 光谱分析: Identifying cellular structure/3-3.ipynb
    - 3-4. 色谱分析: Identifying cellular structure/3-4.ipynb
    - 3-5. 迁移注释: Identifying cellular structure/3-5.ipynb
- 微生物学技术:
    - 4-1. 微生物分离: stages/4-1.ipynb
    - 4-2. 鉴定: stages/4-2.ipynb
    - 4-3. 细菌基因敲除: stages/4-3.ipynb
    - 4-4. 菌种保存: error.md
    - 4-5. 菌种分类: error.md
- 生理学技术:
    - 5-1. 生理信号测定: trajectory/5-1.ipynb
    - 5-2. RNA速率模型: trajectory/5-2.ipynb
    - 5-3. 细胞命运推断: error.md
- 形态学技术:
    - 6-1. 基因调控网络GRN: error.md
    - 6-2. 细胞间通讯: error.md
- 测序文库构建:
    - 7-1. DNA文库: error.md
    - 7-2. RNA-Seq文库: error.md
    - 7-3. 16S文库: error.md
    - 7-4. 宏基因组文库: error.md
- 其他:
    - 8-1. NCBI数据公开: others/7-1.md




plugins:
  - mkdocs-jupyter
  - bibtex:
      bib_file: "docs/ref/ref.bib"
  - search

theme:
  name: material
  custom_dir: docs/overrides

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - footnotes

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

